[mypy]
files = arnio
python_version = 3.9
follow_imports = skip
ignore_missing_imports = True

[mypy-arnio.io]
strict = True
disallow_any_generics = False

[mypy-arnio.cleaning]
ignore_errors = True

[mypy-arnio.quality]
ignore_errors = True

[mypy-arnio.pipeline]
ignore_errors = True

[mypy-arnio.integrations.*]
ignore_errors = True

[mypy-arnio.frame]
ignore_errors = True

[mypy-arnio.convert]
ignore_errors = True

[mypy-arnio.schema]
ignore_errors = True

[mypy-arnio._core]
ignore_errors = True
